### PR TITLE
Added Screenshot of Demo site to ReadMe.md

### PR DESCRIPTION
**Pull request by Neon-K9**
Hello @Ponpon55837 ,

I Added the Screenshot of your Demo Site's Landing Page,
to the '/' root folder under the name of 'screenshot.png'

Hopefully this will help Interested Github users to Understand project in better Manner

Thank you

### CODE REVIEW

**Comment by Neon-K9** [comment]
Hello @Ponpon55837 ,

I hope my PR was helpful,
It would be very nice if you'd consider Merging my PR
And also labelling it as 'hactoberfest-accepted'

Thank You (^_^)

**Comment by Ponpon55837** [comment]
OK. Thanks, I am updating the test website. And updated the screen shot. Thanks for your remind.

**Comment by Neon-K9** [comment]
hey @Ponpon55837 , 

I'm glad that I could be of any help,
please consider labelling this PR as 'hactoberfest-accepted'

Thank you (^_^)

**Comment by Ponpon55837** [comment]
But I need to remind you  that's not hactoberfest  is hac'k'toberfest.

**Comment by Neon-K9** [comment]
Hehe,
my bad,
once again Thanks A lot,
and Happy Hacktoberfest to you!
😅

**Pull request merged**
